### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by AliciaTak** [climate-innovation-hub/frequency-analysis#10]
Hi Damien, the lat coordinates in the ERA5 data are descending instead of ascending like in obs and RCMs. Is it possible to have a functionality in the code to reorder descending lat coordinates?

**Comment by DamienIrving** [comment]
I've made a change that flips the latitude axis if it's descending... https://github.com/climate-innovation-hub/frequency-analysis/commit/c261df9ca903bbb1d6baf3672028760f276671ca

Have a try and let me know if that works :smile:

**Comment by AliciaTak** [comment]
Thank you, @DamienIrving! I tested it, and it works well.
