### ISSUE TITLE
parameters.py line 12

### ISSUE THREAD

**Issue by AliciaTak** [climate-innovation-hub/frequency-analysis#11]
Hi Damien, line 12 <import return_level> in parameters.py causes a ModuleNotFoundError. Is this a package or a module? I googled it but couldn't find anything package-related. Could you please clarify. Thanks!

**Comment by DamienIrving** [comment]
Whoops. Sorry, @AliciaTak.

When I changed the name of `return_period.py` to `eva.py` I forgot to change its name in `parameters.py` (i.e. I import a bunch of the functions from `eva.py` into `parameters.py`).

I've made a new commit to fix it - https://github.com/climate-innovation-hub/frequency-analysis/commit/53c132dbfaaae253ec2d732200b6b6afde95bf7e - so let me know if you have any problems.
