### ISSUE TITLE
Bug in AEP calculations

### ISSUE THREAD

**Issue by tonyrafter** [climate-innovation-hub/frequency-analysis#12]
The AEP calculations in the python code are done naively, that is they don't correctly account for the differences between how ARI and AEP are calculated. This causes all AEP values produced to be higher than they should be.

Example screenshot below showing % difference between 5% AEP from the python code and from the R code (colour scale below):

![Image](https://user-images.githubusercontent.com/18455561/227850190-6d8e9f32-da4a-42ff-99be-ce777128340e.png)
![Image](https://user-images.githubusercontent.com/18455561/227850252-c15ec9e9-8b89-4185-8293-4a0e7b311181.png)

Applying a fix in a separate branch using the method used in the R codebase and will test. Assuming I have it right I'll send a pull request with the corrected code.

**Comment by DamienIrving** [comment]
Thanks for picking this up, @tonyrafter.

I had wondered if I'd misunderstood the difference between an ARI and AEP...

**Comment by tonyrafter** [comment]
I've made the changes and tested on a branch, but I don't seem to have permissions to push my branch to the repo. Can you add that ability @DamienIrving? If you could then I will push the change on my branch and try to do a pull request (first time for everything)

**Comment by DamienIrving** [comment]
No problem, @tonyrafter. I've added you and @AliciaTak as collaborators on this repo.
