### ISSUE TITLE
Incorrect labelling of ARI

### ISSUE THREAD

**Issue by tonyrafter** [climate-innovation-hub/frequency-analysis#14]
ARI should be 'average recurrence interval' (not 'annual return interval')

**Comment by DamienIrving** [comment]
Thanks for catching this, @tonyrafter. I found a few more instances of the incorrect wording: https://github.com/climate-innovation-hub/frequency-analysis/commit/aa7783bbd1c67be924ccc49ef25916abbc215fec

**Comment by tonyrafter** [comment]
No worries – sorry I didn’t think to expand the search beyond the little section I was looking at… Nice job following up 😊

Tony Rafter
Senior Experimental Scientist | CSIRO
***@***.******@***.***> | 03 9239 4508
