### ISSUE TITLE
line 100 in eva.py 

### ISSUE THREAD

**Issue by AliciaTak** [climate-innovation-hub/frequency-analysis#6]
line 100 "chunk_dict['lon'] ": add a case for data with a 'longitude' dimension

**Comment by DamienIrving** [comment]
Good idea - will make this change tomorrow :smile:

**Comment by DamienIrving** [comment]
Resolved by https://github.com/climate-innovation-hub/frequency-analysis/commit/eb11e1976f8b7edc34a034d1ca2e90d6d8dfe232.
