### ISSUE TITLE
unit conversion

### ISSUE THREAD

**Issue by AliciaTak** [climate-innovation-hub/frequency-analysis#7]
Do you find it useful to add functionality to convert other units like K or kg/m2/s to degC and mm/day before running GEV?

**Comment by DamienIrving** [comment]
That would be a good addition. Tomorrow I'll have a go at adding a unit convserion option by implementing the xclim unit conversion function (`xclim.units.convert_units_to`).

**Comment by DamienIrving** [comment]
Resolved by https://github.com/climate-innovation-hub/frequency-analysis/commit/1a794a6a0091b111b657aeac2473426f5a8ff0e0.

I've added an `--output_units` option that can be used to specify what units you want to covert to. By default it figures out the input units from the metadata of the input file, but if the input file doesn't have a units attribute or it has a units attribute that `xclim.units.convert_units_to` doesn't recognise then you can use the `--input_units` option to tell it what the input units are.

**Comment by AliciaTak** [comment]
Thank you @DamienIrving!
