### ISSUE TITLE
Line 294 causes KeyError: 'history' as the 'history' attribute is missing in the input files

### ISSUE THREAD

**Issue by AliciaTak** [climate-innovation-hub/frequency-analysis#8]
Hi Damien, line 294 output_ds.attrs['history'] = get_new_log(args.infiles[0], ds.attrs['history']) causes an error because the input codex files don't have history attributes.

**Comment by DamienIrving** [comment]
Whoops. Sorry, @AliciaTak. I should have anticipated that issue.

I've updated the script so it can handle when the input file doesn't have a history attribute. https://github.com/climate-innovation-hub/frequency-analysis/commit/c43451b6401114eddd662fe083206ece5ed734f0
