### ISSUE TITLE
line 294 still produces KeyError: 'history'

### ISSUE THREAD

**Issue by AliciaTak** [climate-innovation-hub/frequency-analysis#9]
Hi Damien, thanks for tackling this issue, however, the line **if 'history' in ds.attrs['history']:** produces still a KeyError, it might help to change it to **if 'history' in ds.attrs:**?

**Comment by DamienIrving** [comment]
Thanks, @AliciaTak. Sorry about that. I've implemented your fix: https://github.com/climate-innovation-hub/frequency-analysis/commit/904acd89807b710aca68e33671a6750aceefcf94
